### ISSUE TITLE
🛑 TC/Price is down

### ISSUE THREAD

**Issue by secintegration-tc** [tradersclub/TCUptime#15]
In [`0ddfb71`](https://github.com/tradersclub/TCUptime/commit/0ddfb7154ba894eed0929abad5e74d4c56b1192a
), TC/Price (https://tc.tradersclub.com.br/cotacoes) was **down**:
- HTTP code: 200
- Response time: 633 ms

**Comment by douglas-oliveira-tc** [comment]
Falso positivo.
