### ISSUE TITLE
🛑 TC/Educa is down

### ISSUE THREAD

**Issue by secintegration-tc** [tradersclub/TCUptime#31]
In [`ec82e28`](https://github.com/tradersclub/TCUptime/commit/ec82e2808be194260d35debdb01ad7ea21247165
), TC/Educa (https://educa.tc.com.br) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by douglas-oliveira-tc** [comment]
Em investigação.

**Comment by douglas-oliveira-tc** [comment]
Endpoint descontinuado.
